import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { firstName, lastName, email, phone, grade, message, parentName } = body;

    // Validate fields
    if (!firstName || !phone || !grade) {
      return NextResponse.json(
        { success: false, error: 'Name, Phone, and Grade are required.' },
        { status: 400 }
      );
    }

    const recipientEmail = process.env.CONTACT_EMAIL || 'school@cmrschoolkompally.com';
    const resendKey = process.env.RESEND_API_KEY;

    const displayName = lastName ? `${firstName} ${lastName}` : firstName;
    const emailSubject = `New School Enquiry: ${displayName} (Grade ${grade})`;
    const emailBodyHTML = `
      <h2>New Contact / Admissions Enquiry</h2>
      <p><strong>Student Name:</strong> ${displayName}</p>
      ${parentName ? `<p><strong>Parent/Guardian Name:</strong> ${parentName}</p>` : ''}
      <p><strong>Email:</strong> ${email || 'Not Provided'}</p>
      <p><strong>Phone:</strong> ${phone}</p>
      <p><strong>Grade of Interest:</strong> ${grade}</p>
      <p><strong>Message / Additional Details:</strong></p>
      <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #E8620A; font-family: sans-serif;">
        ${(message || 'No additional message.').replace(/\n/g, '<br />')}
      </div>
      <br />
      <hr />
      <p style="font-size: 11px; color: #888;">This email was automatically generated by the CMR School Kompally web contact form.</p>
    `;

    // If Resend API Key is missing, run in development mode (log the request, but return success)
    if (!resendKey || resendKey === 'your_resend_key') {
      console.log('--- DEVELOPMENT MODE (Email Not Sent) ---');
      console.log('Recipient:', recipientEmail);
      console.log('Subject:', emailSubject);
      console.log('Body:', emailBodyHTML);
      console.log('-----------------------------------------');
      
      return NextResponse.json({
        success: true,
        message: 'Enquiry processed in mock mode successfully (keys missing).'
      });
    }

    // Configure Nodemailer with Resend SMTP
    const transporter = nodemailer.createTransport({
      host: 'smtp.resend.com',
      port: 465,
      secure: true, // true for 465, false for other ports
      auth: {
        user: 'resend',
        pass: resendKey,
      },
    });

    // Send email
    await transporter.sendMail({
      from: 'CMR Admissions Form <onboarding@resend.dev>', // Default sender for sandbox, or verified sender in production
      to: recipientEmail,
      subject: emailSubject,
      html: emailBodyHTML,
    });

    return NextResponse.json({ success: true, message: 'Message sent successfully.' });
  } catch (error: any) {
    console.error('Nodemailer SMTP sending error: ', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to dispatch email.' },
      { status: 500 }
    );
  }
}
